Script started on 2021-10-25 09:55:36-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="192" LINES="11"]
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ gcc -g -Wall dynamic.c str.o -o dynamic
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ valgrind --leak-check-[K=yes ./dynamic
==3654== Memcheck, a memory error detector
==3654== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3654== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==3654== Command: ./dynamic
==3654== 
==3654== Conditional jump or move depends on uninitialised value(s)
==3654==    at 0x483EF58: strlen (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3654==    by 0x48D7E94: __vfprintf_internal (vfprintf-internal.c:1688)
==3654==    by 0x48C0EBE: printf (printf.c:33)
==3654==    by 0x109297: main (dynamic.c:38)
==3654== 
u = "c run, c run unix, run unix run"
==3654== Use of uninitialised value of size 8
==3654==    at 0x109529: pstr_cat (str.c:104)
==3654==    by 0x1092AA: main (dynamic.c:40)
==3654== 
==3654== Conditional jump or move depends on uninitialised value(s)
==3654==    at 0x10952E: pstr_cat (str.c:104)
==3654==    by 0x1092AA: main (dynamic.c:40)
==3654== 
==3654== Use of uninitialised value of size 8
==3654==    at 0x10955B: pstr_cat (str.c:108)
==3654==    by 0x1092AA: main (dynamic.c:40)
==3654== 
u = "c run, c run unix, run unix run, go c, go!"
==3654== 
==3654== HEAP SUMMARY:
==3654==     in use at exit: 0 bytes in 0 blocks
==3654==   total heap usage: 2 allocs, 2 frees, 1,067 bytes allocated
==3654== 
==3654== All heap blocks were freed -- no leaks are possible
==3654== 
==3654== Use --track-origins=yes to see where uninitialised values come from
==3654== For lists of detected and suppressed errors, rerun with: -s
==3654== ERROR SUMMARY: 15 errors from 4 contexts (suppressed: 0 from 0)
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ exit
exit

Script done on 2021-10-25 09:56:25-06:00 [COMMAND_EXIT_CODE="0"]
