Script started on 2021-10-25 09:58:51-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ gcc -g -Wall dynamic.c str.o -o dynamic
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ valgrind --leak-check=yes ./dynamic
==3900== Memcheck, a memory error detector
==3900== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3900== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==3900== Command: ./dynamic
==3900== 
==3900== Conditional jump or move depends on uninitialised value(s)
==3900==    at 0x483EF58: strlen (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3900==    by 0x48D7E94: __vfprintf_internal (vfprintf-internal.c:1688)
==3900==    by 0x48C0EBE: printf (printf.c:33)
==3900==    by 0x109277: main (dynamic.c:38)
==3900== 
u = "c run, c run unix, run unix run"
==3900== Use of uninitialised value of size 8
==3900==    at 0x1094FD: pstr_cat (str.c:104)
==3900==    by 0x10928A: main (dynamic.c:40)
==3900== 
==3900== Conditional jump or move depends on uninitialised value(s)
==3900==    at 0x109502: pstr_cat (str.c:104)
==3900==    by 0x10928A: main (dynamic.c:40)
==3900== 
==3900== Use of uninitialised value of size 8
==3900==    at 0x10952F: pstr_cat (str.c:108)
==3900==    by 0x10928A: main (dynamic.c:40)
==3900== 
u = "c run, c run unix, run unix run, go c, go!"
==3900== 
==3900== HEAP SUMMARY:
==3900==     in use at exit: 43 bytes in 1 blocks
==3900==   total heap usage: 2 allocs, 1 frees, 1,067 bytes allocated
==3900== 
==3900== 43 bytes in 1 blocks are definitely lost in loss record 1 of 1
==3900==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==3900==    by 0x10921C: main (dynamic.c:28)
==3900== 
==3900== LEAK SUMMARY:
==3900==    definitely lost: 43 bytes in 1 blocks
==3900==    indirectly lost: 0 bytes in 0 blocks
==3900==      possibly lost: 0 bytes in 0 blocks
==3900==    still reachable: 0 bytes in 0 blocks
==3900==         suppressed: 0 bytes in 0 blocks
==3900== 
==3900== Use --track-origins=yes to see where uninitialised values come from
==3900== For lists of detected and suppressed errors, rerun with: -s
==3900== ERROR SUMMARY: 16 errors from 5 contexts (suppressed: 0 from 0)
]0;ben@Clover-VirtualBox: ~/cse113/lab7[01;32mben@Clover-VirtualBox[00m:[01;34m~/cse113/lab7[00m$ exit
exit

Script done on 2021-10-25 09:59:32-06:00 [COMMAND_EXIT_CODE="0"]
